env:
  node: true

extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:prettier/recommended

parser: '@typescript-eslint/parser'

parserOptions:
  project:
    - './tsconfig.json'

ignorePatterns:
  - node_modules/
  - dist/

plugins:
  - '@typescript-eslint'
  - prettier
  - import

rules:
  no-console:
    - error
    - allow:
      - debug

  no-use-before-define:
    - error
    - functions: false
      classes: false

  import/prefer-default-export: off

  sort-imports:
    - error
    - ignoreCase: false
      ignoreDeclarationSort: true
      ignoreMemberSort: false
      memberSyntaxSortOrder:
        - none
        - all
        - multiple
        - single
      allowSeparatedGroups: true

settings:
  import/resolver:
    typescript:
    node:
      extensions: ['.mjs', '.cjs', '.js', '.jsx', '.json', '.mts', '.cts', '.ts', '.tsx', '.d.ts']
