env:
  node: true
  jest/globals: true

extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:prettier/recommended
  - plugin:jest/recommended

parser: '@typescript-eslint/parser'

parserOptions:
  project:
    - './tsconfig.json'

ignorePatterns:
  - node_modules/
  - dist/

plugins:
  - '@typescript-eslint'
  - prettier
  - import
  - jest

rules:
  import/prefer-default-export: off
  import/extensions:
    - error
    - never
    - json: always

  sort-imports:
    - error
    - ignoreCase: false
      ignoreDeclarationSort: true
      ignoreMemberSort: false
      memberSyntaxSortOrder:
        - none
        - all
        - multiple
        - single
      allowSeparatedGroups: true

settings:
  import/resolver:
    typescript:
    node:
      extensions: ['.mjs', '.cjs', '.js', '.jsx', '.json', '.mts', '.cts', '.ts', '.tsx', '.d.ts']
